services:
  remnawave-tg-shop:
    # image: ghcr.io/machka-pasla/remnawave-tg-shop:latest
    build: .
    container_name: remnawave-tg-shop
    hostname: remnawave-tg-shop
    env_file:
      - .env
    networks:
      - remnawave-network
    volumes:
      - ./locales:/app/locales
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      remnawave-caddy:
        condition: service_started
      remnawave-tg-shop-db:
        condition: service_healthy

  remnawave-tg-shop-db:
    image: postgres:17
    container_name: remnawave-tg-shop-db
    hostname: remnawave-tg-shop-db
    env_file:
      - .env
    volumes:
      - ./app-data/pgdb:/var/lib/postgresql/data
    networks:
      - remnawave-network
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
  # remnawave-tg-shop-db-backup:
  #   image: kartoza/pg-backup:17-3.5
  #   container_name: remnawave-tg-shop-db-backup
  #   depends_on:
  #     - remnawave-tg-shop-db
  #   env_file:
  #     - .env
  #   networks:
  #     - remnawave-network
  #   environment:
  #     POSTGRES_HOST: remnawave-tg-shop-db
  #     POSTGRES_PORT: 5432
  #     RUN_AS_ROOT: true
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASS: ${POSTGRES_PASSWORD}
  #     ARCHIVE_FILENAME: "$(date +%Y)/$(date +%B)/TG-BOT-DMP.$(date +%d-%B-%Y-%H-%M)"
  #     DBLIST: postgres
  #     CONSOLE_LOGGING: TRUE
  #     CRON_SCHEDULE: "0 21,9 * * *" # каждая минута для теста
  #     REMOVE_BEFORE: "7" # удалять старые бэкапы старше 7 дней
  #   volumes:
  #     - ./app-data/backups:/backups
  #   restart: on-failure
  remnawave-caddy:
    image: caddy:latest
    container_name: remnawave-caddy
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - remnawave-network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

networks:
  remnawave-network:
    external: false

volumes:
  caddy_data:
  caddy_config:
